### ISSUE TITLE
chrome 106 打开时出现js报错

### ISSUE THREAD

**Issue by f0re1gnKey** [msgbyte/tailchat-meeting#11]
页面空白，f12控制台显示

首次打开出现
index.2becea3b.js:29 TypeError: Cannot read properties of null (reading 'split')
    at children (index.2becea3b.js:216:14058)
    at g.value (index.2becea3b.js:184:12117)
    at _1 (index.2becea3b.js:29:61786)
    at k3 (index.2becea3b.js:29:61580)
    at X8 (index.2becea3b.js:31:9163)
    at Y8 (index.2becea3b.js:31:855)
    at bN (index.2becea3b.js:31:780)
    at T1 (index.2becea3b.js:29:85798)
    at index.2becea3b.js:29:37111
    at t.unstable_runWithPriority (index.2becea3b.js:21:3867)

切换布局或其他情况显示
TypeError: Failed to execute 'unobserve' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at Room.c528d359.js:171:67913
    at n_ (index.223f53a5.js:34:22565)
    at Ed (index.223f53a5.js:34:24276)
    at Vl (index.223f53a5.js:34:42008)
    at v4 (index.223f53a5.js:34:36876)
    at Ts (index.223f53a5.js:32:3279)
    at F2 (index.223f53a5.js:34:37254)
    at Object.notify (index.223f53a5.js:34:59049)
    at Object.o [as notifyNestedSubs] (index.223f53a5.js:34:59505)
    at a (index.223f53a5.js:34:59546)

**Comment by moonrailgun** [comment]
我目前没有更多的精力去排查这个问题，如果可能的话可以提供调用split这个操作的截图么？

方法是报错的时候点击报错的堆栈`index.2becea3b.js:216:14058`
